{{- if .Values.crunchyPostgres.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    \c {{ .Release.Name }}
    GRANT CREATE ON SCHEMA public TO "{{ .Release.Name }}";
{{- end }}